# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b934b70bc99180665d1391c46db7a97349e9b9a72bfeb475b5fdb644d64f0d7a682b98c79a9b08b173ec070d49aebed3458f6e9b0bef3efad9b42e19b0175ac8

test:
  secret_key_base: 3702d7539d2089c9f17c122f230f89b2a9d811dc827332826b1a5b0ae1ce09fee3b275b462516eb86ba66c3189e004b6e457bf23abfaf5c0704c2fe047387425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
